### ISSUE TITLE
✨ Rules.Widget - Reproduce the functionality using commits.json

### ISSUE THREAD

**Issue by Aibono1225** [SSWConsulting/SSW.Rules.Widget#39]
Cc: @bradystroud @BrookJeynes 

To Myself,

### Pain
Currently, we are working on updating the Rules.Widget in order to minimize the number of requests to the GitHub API.

![image](https://github.com/SSWConsulting/SSW.Rules.Widget/assets/127192800/767a1d60-b3ee-4e48-89ab-7e181139da34)
**Figure: Too many requests**

### Suggested Solution
Retrieve widget data from a JSON file instead of using the GitHub API.

### Tasks
- [x] Add a script to create `commits.json` containing the data needed for the Widget
- [x] Automate the script in the Azure Pipeline to keep the `commits.json` file up to date
- [x] Update the Widget to use the data from the JSON file as its new data source

**Comment by Aibono1225** [comment]
Done - we are now using https://ssw.com.au/rules/commits.json to fetch the data
